---
title: "The influence of popularity on Tame Impala"
author: "Puck Voorham"
date: "2023-02-21"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r, echo=FALSE}

library(tidyverse)
library(plotly)
library(spotifyr)
library(compmus)

```
### Introduction

***
This is text 

### A first visualisation

```{r}
Before_Currents <- get_playlist_audio_features("", "0zj7vBkFkrtkIy7bbiIDHT")
After_Currents <- get_playlist_audio_features("", "2iF5St3YBr1AalBJFZK8uD")

Categorical <- rbind(Before_Currents, After_Currents)

Categorical |>
  ggplot(aes(x = playlist_name, y = danceability )) +
  geom_violin()
```

*** 
deze plot 

### A second visualisation

```{r}
scatter_plot <- ggplot(Categorical, aes(x = valence, y = energy, size = tempo, color = playlist_name)) +
  geom_point() +
  labs(
    x = "Valence",
    y = "Energy"
  )

scatter_plot

```


***
deze plot is 



### Chromatogram test

```{r}

Categorical <-
  get_tidy_audio_analysis("6qi0vMwfN9qRh8wzrOyvp7") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)


Categorical |>
  mutate(pitches = map(pitches, compmus_normalise, "manhattan")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```

*** 
Does this work?

### Conclusion

***
Here I would write my overall conclusions so far
